"""Imports item icons from game-icons.net into the interface and writes CREDITS.md.

The icons are single-colour silhouettes licensed under CC BY 3.0 (see CREDITS.md).
To keep them in the game's hand-drawn style, the interface paints each one with the
same metal/wood/leather gradients, dark outline and sheen as the built-in art.

Usage (from the repository root):
    git clone --depth 1 https://github.com/game-icons/icons /tmp/game-icons
    python tools/import_game_icons.py /tmp/game-icons

It rewrites the block between the `<licensed-icons>` markers in aeterna/ui/index.html
and regenerates CREDITS.md. Edit ICONS below to add or change icons.
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGE = os.path.join(ROOT, 'aeterna', 'ui', 'index.html')
CREDITS = os.path.join(ROOT, 'CREDITS.md')
START, END = '            // <licensed-icons>\n', '            // </licensed-icons>\n'

AUTHORS = {
    'lorc': ('Lorc', 'https://lorcblog.blogspot.com'),
    'delapouite': ('Delapouite', 'https://delapouite.com'),
    'willdabeast': ('Willdabeast', 'http://wjbstories.blogspot.com'),
}

# (game key, "author/icon-name", material, look on the player figure, what it is used for)
# Materials: steel, bronze, gold, leather, wood, red. The look is a built-in icon the player
# figure (ART.avatar) uses to draw the item when it is equipped.
ICONS = [
    ('gi_broadsword', 'lorc/broadsword', 'steel', 'weapon_2', 'Centurion Sword'),
    ('gi_battle_axe', 'lorc/battle-axe', 'steel', 'weapon_9', 'Dolabra Axe'),
    ('gi_flanged_mace', 'delapouite/flanged-mace', 'steel', 'weapon_8', 'Flanged Mace'),
    ('gi_glaive', 'delapouite/glaive', 'steel', 'weapon_6', 'Falcata'),
    ('gi_spiked_mace', 'lorc/spiked-mace', 'wood', 'weapon_8', 'Spiked Club'),
    ('gi_crested_helmet', 'lorc/crested-helmet', 'bronze', 'helmet_4', 'Legionary Helm'),
    ('gi_light_helm', 'delapouite/light-helm', 'bronze', 'helmet_1', 'Montefortino Helm'),
    ('gi_spartan_helmet', 'delapouite/spartan-helmet', 'bronze', 'helmet_4', 'Corinthian Helm'),
    ('gi_centurion_helmet', 'delapouite/centurion-helmet', 'gold', 'helmet_2', 'Praetorian Helm'),
    ('gi_visored_helm', 'lorc/visored-helm', 'steel', 'helmet_3', 'Visored Helm'),
    ('gi_breastplate', 'lorc/breastplate', 'bronze', 'armor_3', 'Bronze Breastplate'),
    ('gi_abdominal_armor', 'delapouite/abdominal-armor', 'bronze', 'armor_3', 'Muscle Cuirass'),
    ('gi_lamellar', 'lorc/lamellar', 'steel', 'armor_4', 'Lamellar Cuirass'),
    ('gi_leather_armor', 'delapouite/leather-armor', 'leather', 'armor_leather', 'Linothorax'),
    ('gi_bordered_shield', 'lorc/bordered-shield', 'red', 'shield_1', 'Tower Shield'),
    ('gi_round_shield', 'willdabeast/round-shield', 'bronze', 'shield_2', 'Hoplite Aspis'),
    ('gi_spiked_shield', 'delapouite/spiked-shield', 'steel', 'shield_3', 'Spiked Buckler'),
    ('gi_ring', 'delapouite/ring', 'steel', 'ring_1', 'Iron Legion Ring'),
    ('gi_diamond_ring', 'delapouite/diamond-ring', 'gold', 'ring_1', 'Jeweled Ring'),
    ('gi_gem_pendant', 'lorc/gem-pendant', 'gold', 'amulet_1', 'Bulla Pendant'),
    ('gi_emerald_necklace', 'delapouite/emerald-necklace', 'gold', 'amulet_1', 'Emerald Necklace'),
    ('gi_gauntlet', 'delapouite/gauntlet', 'steel', 'gloves_1', 'Mailed Gauntlet'),
    ('gi_leather_boot', 'lorc/leather-boot', 'leather', 'shoes_1', 'Legionary Boots'),
    ('gi_metal_boot', 'delapouite/metal-boot', 'steel', 'shoes_1', 'Armored Caligae'),
]


def icon_paths(clone, source):
    with open(os.path.join(clone, source + '.svg'), encoding='utf-8') as f:
        svg = f.read()
    paths = [d for d in re.findall(r'<path[^>]*\sd="([^"]+)"', svg) if d != 'M0 0h512v512H0z']
    if not paths:
        raise SystemExit('No icon path found in %s' % source)
    return ' '.join(paths)


def main(clone):
    data = {}
    for key, source, material, look, _ in ICONS:
        author = source.split('/')[0]
        data[key] = {'d': icon_paths(clone, source), 'm': material, 'look': look, 'by': AUTHORS[author][0]}
    block = (START
             + '            // Item icons from game-icons.net (CC BY 3.0, see CREDITS.md), generated by\n'
             + '            // tools/import_game_icons.py. Painted in the game\'s style by licensedIcon() below.\n'
             + '            const LICENSED_ICONS = ' + json.dumps(data, separators=(',', ':')) + ';\n'
             + END)
    with open(PAGE, encoding='utf-8') as f:
        page = f.read()
    a, b = page.index(START), page.index(END) + len(END)
    with open(PAGE, 'w', encoding='utf-8') as f:
        f.write(page[:a] + block + page[b:])

    lines = ['# Credits', '',
             'All of the game\'s art is hand-drawn SVG made for Aeterna Roma, except the item icons below.', '',
             '## Item icons from [game-icons.net](https://game-icons.net)', '',
             'Licensed under [Creative Commons Attribution 3.0](https://creativecommons.org/licenses/by/3.0/).',
             'Changes: recoloured with the game\'s metal, wood and leather gradients, outlined, and given a sheen.', '',
             '| Icon | Author | Used for |', '|---|---|---|']
    for key, source, _, _, used_for in ICONS:
        author, name = source.split('/')
        label, site = AUTHORS[author]
        lines.append('| [%s](https://game-icons.net/1x1/%s/%s.html) | [%s](%s) | %s |'
                     % (name, author, name, label, site, used_for))
    with open(CREDITS, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print('Imported %d icons; wrote %s' % (len(ICONS), os.path.relpath(CREDITS, ROOT)))


if __name__ == '__main__':
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    main(sys.argv[1])
